
<div style="background: linear-gradient(90deg, #0ea5e9, #a78bfa, #22c55e);
            color: white; padding: 30px 26px; border-radius: 18px;
            box-shadow: 0 10px 24px rgba(0,0,0,0.12);">
  <h1 style="margin: 0; font-size: 2.35rem;">🐍 Python + NumPy Foundations for Machine Learning</h1>
  <p style="margin-top: 10px; font-size: 1.15rem;">
    A explanation-first notebook that builds Python programming skills through ML-friendly examples.
  </p>
</div>



<div style="background:#111827; color:white; padding: 14px 16px; border-radius: 12px;">
  <h2 style="margin:0;">🧪 0) Quick environment sanity check</h2>
</div>



If you are using the course environment (e.g., `mlpy13`), this cell should run without errors.


In [1]:
import sys
print("Python version:", sys.version.split()[0])

import numpy as np
print("NumPy version:", np.__version__)

Python version: 3.11.7
NumPy version: 1.26.4



<div style="background: linear-gradient(90deg, #f97316, #facc15);
            color: #111827; padding: 14px 16px; border-radius: 12px;">
  <h2 style="margin:0;">1) Python essentials for ML thinking</h2>
</div>



### 1.1 Variables and dynamic typing

Python is **dynamically typed**: you don't declare types upfront.
The type is inferred from the value.

This is convenient for rapid experimentation — a common ML workflow style.


In [2]:
x = 10
y = 3.5
name = "model"

print(type(x), x)
print(type(y), y)
print(type(name), name)

<class 'int'> 10
<class 'float'> 3.5
<class 'str'> model


In [3]:
type(x)

int


**Why this output?**  
`type()` reveals the runtime type. Python decides the type based on the assigned value.


In [4]:
c = 2 + 3j          # complex
b = True            # bool
print("complex:", c, type(c))
print("bool:", b, type(b))

complex: (2+3j) <class 'complex'>
bool: True <class 'bool'>


In [5]:
s = "machine learning"
S = 'MACHINE'
print("str:", s, type(s))
print("Upper:", s.upper())
print("Length:", len(s))

str: machine learning <class 'str'>
Upper: MACHINE LEARNING
Length: 16


In [6]:
S.lower()

'machine'


### 1.2 Numeric operations and type promotion

When you combine integers and floats, Python typically promotes to float
to preserve information.


In [7]:
# This is my 1st pyhon pro.
a = 5
b = 2
c = 5 / 2
d = 5 // 2
e = 5 * 2.0
f = 5 ** 2

print("5/2 =", c)
print("5//2 =", d)
print("5 * 2.0 =", e, "type:", type(e))

5/2 = 2.5
5//2 = 2
5 * 2.0 = 10.0 type: <class 'float'>


In [8]:
f

25

#### This is my 1st python class
**Why this output?**  
- `/` always returns a float in Python 3.  
- `//` is floor division.  
- `int * float` produces a `float` (type promotion).



### 1.3 Booleans and comparisons

These are tiny but crucial in ML for filtering data and building conditions.


In [9]:
accuracy = 0.82
threshold = 0.80

print("Pass?", accuracy >= threshold)
print("Not pass?", accuracy < threshold)

Pass? True
Not pass? False



**Why this output?**  
Comparison operators return Boolean values (`True`/`False`).



### 1.4 Strings (quick, practical)

You’ll use strings for column names, file paths, labels, and logging.


In [10]:
feature = "age"
print(feature.upper())
print(f"Selected feature: {feature}")

AGE
Selected feature: age



**Why this output?**  
- `.upper()` returns an uppercase copy of the string.  
- f-strings embed variables cleanly — great for readable ML logs.



<div style="background:#f5f3ff; border-left: 6px solid #8b5cf6; padding: 14px 16px; border-radius: 10px;">
  <h3 style="margin-top:0;">1.5 Core data structures</h3>
  <p style="margin-bottom:0;">
    Lists, tuples, dictionaries, and sets show up constantly in ML data prep and configuration.
  </p>
</div>



#### Lists: ordered, mutable


In [11]:
values = [10, 20, 30] # Vector
values.append(40)
print(values)
print("First element:", values[2])

[10, 20, 30, 40]
First element: 30



**Why this output?**  
Lists store an ordered sequence. `append` mutates the list in-place.



#### Tuples: ordered, immutable


In [12]:
shape = (3, 4)
print(shape)
print("Rows:", shape[0])

(3, 4)
Rows: 3



**Why this output?**  
Tuples are often used for fixed metadata like `(rows, cols)`.


In [13]:
t1 = (1)
print(t1, type(t1))

t2 = (1,)
print(t2, type(t2))  

t3 = 1,
print(t3, type(t3)) 

1 <class 'int'>
(1,) <class 'tuple'>
(1,) <class 'tuple'>


In [14]:
# We visually associate () with tuples, but Python uses the comma to define a tuple.
lst = [1, 2, 3]
tup = (1, 2, 3)

lst[0] = 99
print("List changed:", lst)
# Exceptional or error handling.
try:
    tup[0] = 99
except TypeError as e:
    print("Tuple error:", e)

List changed: [99, 2, 3]
Tuple error: 'tuple' object does not support item assignment


In [15]:
#List = mutable (you can edit)
#Tuple = immutable (you can’t edit)


#### Dictionaries: key-value mapping


In [16]:
# First: Key and second is Value
metrics = {"kishore": 0.92, "f1": 0.88}
metrics["recall"] = 0.85
print(metrics)
print("Accuracy:", metrics["kishore"])

{'kishore': 0.92, 'f1': 0.88, 'recall': 0.85}
Accuracy: 0.92



**Why this output?**  
Dictionaries map keys to values — perfect for storing experiment results.



#### Sets: unique elements


In [17]:
labels = {"cat", "dog", "cat", "bird"}
print(labels)

{'dog', 'cat', 'bird'}



**Why this output?**  
A set removes duplicates automatically.


In [18]:
print([1, 2] + [3, 4])
print((1, 2) + (3, 4))
# Concatenation and repetition (works for both)
print([1, 2] * 3)
print((1, 2) * 3)

[1, 2, 3, 4]
(1, 2, 3, 4)
[1, 2, 1, 2, 1, 2]
(1, 2, 1, 2, 1, 2)


In [19]:
lst = [1, 2, 3]
tup = (1, 2, 3)
#lst + 10
try:
    print(lst + 10)
except TypeError as e:
    print("List + int error:", e)

try:
    print(tup + 10)
except TypeError as e:
    print("Tuple + int error:", e)

List + int error: can only concatenate list (not "int") to list
Tuple + int error: can only concatenate tuple (not "int") to tuple


In [20]:
# How to 10 to all the elements in the list
lst = [1, 2, 3]
tup = (1, 2, 3)

lst_plus_10 = [x + 10 for x in lst]
tup_plus_10 = tuple(x + 10 for x in tup)

print(lst_plus_10)
print(tup_plus_10)

[11, 12, 13]
(11, 12, 13)


In [21]:
# IN ML - Make a list of features
features = []
features.append("age")
features.append("salary")
features.append("department")
print(features)

['age', 'salary', 'department']


In [22]:
# Collecting metrics during training
loss_history = []
for epoch in range(3):
    loss = 0.1 / (epoch + 1)  
    loss_history.append(loss)

print(loss_history)

[0.1, 0.05, 0.03333333333333333]


*List* → data you intend to grow or edit &&
*Tuple* → data you want to keep fixed and safe

### 1.6 Indexing and slicing
You’ll use slicing everywhere: sequences, arrays, and time windows.

In [23]:
data = [0, 1, 2, 3, 4, 5]
print("data[1:4] =", data[1:4])
print("data[:3] =", data[:3])
print("data[3:] =", data[3:])
print("data[::2] =", data[::2])

data[1:4] = [1, 2, 3]
data[:3] = [0, 1, 2]
data[3:] = [3, 4, 5]
data[::2] = [0, 2, 4]



**Why this output?**  
Slicing uses `[start:stop:step]` and returns a new list with the selected pattern.



### 1.7 Control flow (if/for)

Control flow helps build custom experiments, quick checks, and data rules.


In [24]:
score = 78
if score >= 90:
    grade = "A"
elif score >= 75:
    grade = "B"
else:
    grade = "C"

print("Grade:", grade)

Grade: B



**Why this output?**  
Python executes the first matching branch.


In [25]:
total = 0
for v in [1, 2, 3, 4]:
    total += v
print("Sum:", total)


Sum: 10



**Why this output?**  
The loop accumulates values sequentially.


In [26]:
loss_history = [] # Empty list
# iteration
for epoch in range(1, 6):
    # pretend loss decreases
    loss = 1 / epoch
    loss_history.append(loss)
    print(f"Epoch {epoch}: loss={loss:.4f}")

Epoch 1: loss=1.0000
Epoch 2: loss=0.5000
Epoch 3: loss=0.3333
Epoch 4: loss=0.2500
Epoch 5: loss=0.2000


In [27]:
X = list(range(20))  # dummy data
batch_size = 5
for start in range(0, len(X), batch_size):
    batch = X[start:start + batch_size]
    print("Batch:", batch)

Batch: [0, 1, 2, 3, 4]
Batch: [5, 6, 7, 8, 9]
Batch: [10, 11, 12, 13, 14]
Batch: [15, 16, 17, 18, 19]


In [28]:
r = range(20)
r[19]

19

In [29]:
# Loop with ENUMERATE
models = ["logreg", "svm", "rf"]
for i, model in enumerate(models, start=1):
    print(i, model)

1 logreg
2 svm
3 rf


In [30]:
# Loop Using Zip
true = [1, 0, 1, 1]
pred = [1, 0, 0, 1]

correct = 0
for t, p in zip(true, pred):
    if t == p:
        correct += 1
print("Accuracy:", correct / len(true))

Accuracy: 0.75



### 1.8 List and dict comprehensions

Comprehensions are Pythonic and concise — useful for feature transforms.


In [31]:
nums = [1, 2, 3, 4, 5]
squares = [n**2 for n in nums]
even_squares = [n**2 for n in nums if n % 2 == 0]
print("Squares:", squares)
print("Even squares:", even_squares)

Squares: [1, 4, 9, 16, 25]
Even squares: [4, 16]



**Why this output?**  
Comprehensions combine looping + optional filtering into a compact expression.



<div style="background: linear-gradient(90deg, #22c55e, #0ea5e9);
            color:white; padding: 14px 16px; border-radius: 12px;">
  <h2 style="margin:0;">2) Functions for reusable ML code</h2>
</div>



Functions help you avoid copy-paste in notebooks and build clean utilities.


In [1]:
def minmax_scale(values):
    vmin = min(values)
    vmax = max(values)
    #return [(v - vmin) / (vmax - vmin) for v in values]
    return [v/vmax for v in values]
sample = [10, 12, 15, 20] # All values between 0 and 1 -Normalization
print(minmax_scale(sample))

[0.5, 0.6, 0.75, 1.0]



**Why this output?**  
We compute the minimum/maximum, then scale each value to the `[0, 1]` range.
This mirrors the idea behind `MinMaxScaler` in scikit-learn, but implemented in pure Python.



### 🧩 Practice
Write a function `standardize(values)` that returns z-scores for a Python list.



<div style="background:#fff1f2; border-left: 6px solid #ef4444; padding: 14px 16px; border-radius: 10px;">
  <h3 style="margin-top:0;">2.1 Errors and exceptions (light but important)</h3>
  <p style="margin-bottom:0;">
    Good ML code fails gracefully when data is messy.
  </p>
</div>


In [2]:
# Function in python
def safe_inverse(x):
    try:
        return 1 / x
    except ZeroDivisionError:
        return None

print(safe_inverse(5))
print(safe_inverse(0))

0.2
None



**Why this output?**  
Division by zero raises `ZeroDivisionError`. We catch it and return `None` to signal an invalid result.



<div style="background: linear-gradient(90deg, #8b5cf6, #ec4899);
            color:white; padding: 14px 16px; border-radius: 12px;">
  <h2 style="margin:0;">3) NumPy: the engine under ML</h2>
</div>



NumPy arrays power:
- fast numeric computation  
- vectorized operations  
- memory-efficient data representation  

Most ML libraries expect NumPy-like inputs.



### 3.1 Creating arrays


In [68]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.zeros((2, 3))
c = np.ones((3, 2))
d = np.arange(0, 10, 2)
e = np.linspace(0, 1, 5)

print("a:", a)
print("b:\n", b)
print("c:\n", c)
print("d:", d)
print("e:", e)

a: [1 2 3 4]
b:
 [[0. 0. 0.]
 [0. 0. 0.]]
c:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
d: [0 2 4 6 8]
e: [0.   0.25 0.5  0.75 1.  ]



**Why this output?**  
- `array` converts a Python list into a contiguous numeric array.  
- `zeros/ones` create arrays of a given shape.  
- `arange` uses step-size arithmetic.  
- `linspace` creates evenly spaced values between endpoints.


**How Arrays are different from Tuple and List?**  
- `lists` Mixed style data with string, numeric, bool.  


### 3.2 dtypes and why they matter


In [4]:
import numpy as np
x_int = np.array([1, 2, 3], dtype=np.int8) # 32 bit signed integer
x_float = np.array([1, 2, 3], dtype=np.float32)

print(x_int.dtype, x_int)
print(x_float.dtype, x_float)

int8 [1 2 3]
float32 [1. 2. 3.]



**Why this output?**  
`dtype` controls how numbers are stored in memory.
This affects performance and compatibility with ML frameworks.


In [36]:
# Type behavior (very important for ML)
mixed_list = [1, 2.5, "three", True]
print("Mixed list:", mixed_list)

arr_auto = np.array([1, 2.5, 3])
print("NumPy auto dtype:", arr_auto, arr_auto.dtype)

arr_i32 = np.array([1, 2, 3], dtype=np.int32)
arr_f32 = np.array([1, 2, 3], dtype=np.float32)

print("int32 array:", arr_i32, arr_i32.dtype)
print("float32 array:", arr_f32, arr_f32.dtype)

Mixed list: [1, 2.5, 'three', True]
NumPy auto dtype: [1.  2.5 3. ] float64
int32 array: [1 2 3] int32
float32 array: [1. 2. 3.] float32


#### Why NumPy is the ML default — vectorized math?

In [7]:
arr = np.array([1, 2, 3, 4])

print("arr:", arr)
print("arr / 10:", arr / 10)
print("arr * 2:", arr * 2)
print("arr ** 2:", arr ** 2)
print("mean:", arr.mean())
print("sum:", arr.sum())

arr: [1 2 3 4]
arr / 10: [0.1 0.2 0.3 0.4]
arr * 2: [2 4 6 8]
arr ** 2: [ 1  4  9 16]
mean: 2.5
sum: 10


In [38]:
# Cell 8: The equivalent list operations need loops/comprehensions

lst = [1, 2, 3, 4]

print("list + list:", lst + [5, 6])
print("list * 2:", lst * 2)

# element-wise numeric operation
print([x + 10 for x in lst])
print([x * 2 for x in lst])

list + list: [1, 2, 3, 4, 5, 6]
list * 2: [1, 2, 3, 4, 1, 2, 3, 4]
[11, 12, 13, 14]
[2, 4, 6, 8]


#### Conversions between list/tuple and NumPy arrays

In [39]:
lst = [1, 2, 3]
tup = (1, 2, 3)

arr_from_list = np.array(lst)
arr_from_tuple = np.array(tup)

print(arr_from_list, arr_from_list.dtype)
print(arr_from_tuple, arr_from_tuple.dtype)

# Convert back
print(arr_from_list.tolist(), type(arr_from_list.tolist()))
print(tuple(arr_from_tuple.tolist()))

[1 2 3] int32
[1 2 3] int32
[1, 2, 3] <class 'list'>
(1, 2, 3)


#### Memory comparison (conceptual + practical)

In [40]:
n = 1000
py_list = list(range(n)) # a Python list of 1000 integers
py_tuple = tuple(range(n)) # a Python tuple of 1000 integers

np_int32 = np.arange(n, dtype=np.int32) # a NumPy array of 1000 integers stored as int32
np_int64 = np.arange(n, dtype=np.int64) # a NumPy array of 1000 integers stored as int64

print("Python list container size:", sys.getsizeof(py_list)) 
# Lists/tuples store pointers to objects
print("Python tuple container size:", sys.getsizeof(py_tuple))
print("One Python int size:", sys.getsizeof(1))

print("\nNumPy int32 object size:", sys.getsizeof(np_int32))
print("NumPy int32 data bytes (nbytes):", np_int32.nbytes)

print("\nNumPy int64 object size:", sys.getsizeof(np_int64))
print("NumPy int64 data bytes (nbytes):", np_int64.nbytes)

Python list container size: 8056
Python tuple container size: 8040
One Python int size: 28

NumPy int32 object size: 4112
NumPy int32 data bytes (nbytes): 4000

NumPy int64 object size: 8112
NumPy int64 data bytes (nbytes): 8000


# In C
### An integer is typically a fixed-size value:
### int often 4 bytes
### long long often 8 bytes
### It’s basically just the raw bits for the number.

# In Python

### An int is a full object that includes: the number’s value
### plus metadata like:its type info
### bookkeeping used by Python internally support for arbitrarily large integers
# So even the number 1 takes much more than 4 or 8 bytes in memory.

In [41]:
import sys
import struct

# Simple numeric values
i = 1                 # int
f = 1.0               # float
b = True              # bool
c = 1 + 0j            # complex

print("=== Python object sizes (bytes) ===")
print("int(1):     ", sys.getsizeof(i))
print("float(1.0): ", sys.getsizeof(f))
print("bool(True): ", sys.getsizeof(b))
print("complex(1+0j):", sys.getsizeof(c))

print("\n=== Container overhead examples ===")
lst = [1]
tup = (1,)
print("list with one int:", sys.getsizeof(lst), " + element object:", sys.getsizeof(lst[0]))
print("tuple with one int:", sys.getsizeof(tup), " + element object:", sys.getsizeof(tup[0]))

=== Python object sizes (bytes) ===
int(1):      28
float(1.0):  24
bool(True):  28
complex(1+0j): 32

=== Container overhead examples ===
list with one int: 64  + element object: 28
tuple with one int: 48  + element object: 28


# Python int = object-heavy
# NumPy int32 = compact 4-byte raw value

In [42]:
import numpy as np

print("=== NumPy raw storage size per element (bytes) ===")
print("int32 :", np.dtype(np.int32).itemsize)
print("int64 :", np.dtype(np.int64).itemsize)
print("float32:", np.dtype(np.float32).itemsize)
print("float64:", np.dtype(np.float64).itemsize)

arr_py = [1]*1000
arr_np = np.ones(1000, dtype=np.int32)

print("\nPython list object size:", sys.getsizeof(arr_py))
print("NumPy array object size:", sys.getsizeof(arr_np))
print("NumPy data buffer bytes:", arr_np.nbytes)

=== NumPy raw storage size per element (bytes) ===
int32 : 4
int64 : 8
float32: 4
float64: 8

Python list object size: 8056
NumPy array object size: 4112
NumPy data buffer bytes: 4000


# For ML, NumPy arrays are far more memory-efficient than Python lists.


### 3.3 Shape, ndim, and reshape


In [10]:
m = np.arange(12) # 1-D dimensional vector
print("m:", m)
print("shape:", m.shape, "ndim:", m.ndim)
# Converting 1D to 2D matrix
m2 = m.reshape(3, 4)
print("m2:\n", m2)
print("m2 shape:", m2.shape)

m: [ 0  1  2  3  4  5  6  7  8  9 10 11]
shape: (12,) ndim: 1
m2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
m2 shape: (3, 4)



**Why this output?**  
- `shape` shows dimensions.  
- `reshape` reinterprets the same data into a new layout (when compatible).



### 3.4 Indexing, slicing, and views


In [12]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[-3:])

[20 30 40]
[30 40 50]


In [45]:
mat = np.arange(1, 10).reshape(3, 3)
print(mat)
print("Row 0:", mat[0])
print("Column 1:", mat[:, 1])
print("Sub-matrix:\n", mat[:2, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row 0: [1 2 3]
Column 1: [2 5 8]
Sub-matrix:
 [[1 2]
 [4 5]]



**Why this output?**  
NumPy supports multi-axis slicing using `array[row_slice, col_slice]`.



### 3.5 Boolean masking


In [46]:
scores = np.array([45, 60, 75, 90, 30])
mask = scores >= 70

print("Mask:", mask)
print("Selected:", scores[mask])

Mask: [False False  True  True False]
Selected: [75 90]



**Why this output?**  
The comparison creates a Boolean array. Using it as an index filters values.



### 3.6 Vectorization vs Python loops


In [47]:
py_list = list(range(1, 6))
loop_out = []
for v in py_list:
    loop_out.append(v * 2)

np_arr = np.array(py_list)
vec_out = np_arr * 2

print("Loop output:", loop_out)
print("Vectorized output:", vec_out)

Loop output: [2, 4, 6, 8, 10]
Vectorized output: [ 2  4  6  8 10]



**Why this output?**  
Both compute the same math, but NumPy uses optimized C backends under the hood.



### 3.7 Broadcasting


In [48]:
A = np.ones((3, 3))
b = np.array([1, 2, 3])

print("A:\n", A)
print("b:", b)
print("A + b:\n", A + b)

A:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
b: [1 2 3]
A + b:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]



**Why this output?**  
`b` is treated as a row vector and automatically expanded to match `A`'s shape.



### 3.8 Aggregations with axis


In [49]:
X = np.arange(1, 13).reshape(3, 4)
print(X)

print("Sum all:", X.sum())
print("Sum by rows (axis=1):", X.sum(axis=1))
print("Sum by cols (axis=0):", X.sum(axis=0))
print("Mean by cols:", X.mean(axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sum all: 78
Sum by rows (axis=1): [10 26 42]
Sum by cols (axis=0): [15 18 21 24]
Mean by cols: [5. 6. 7. 8.]



**Why this output?**  
`axis=0` computes per column, `axis=1` computes per row.



### 3.9 Random numbers + reproducibility


In [32]:
# random number generator
rng = np.random.default_rng() # Remove 42 and execute and with 42
samples = rng.normal(loc=0.0, scale=1.0, size=5)
print(samples)

[-1.20635435 -1.2807101   0.32679265  0.44731519  0.99413913]



**Why this output?**  
Using a fixed seed makes results repeatable.



### 3.10 Linear algebra essentials


In [51]:
W = np.array([[1, 2], [3, 4]]) # Define a Matrix
v = np.array([10, 20])
print(W.shape)
print("W:\n", W)
print("v:", v)
print("Matrix-vector product W @ v:", W @ v)
print("Transpose W.T:\n", W.T)

(2, 2)
W:
 [[1 2]
 [3 4]]
v: [10 20]
Matrix-vector product W @ v: [ 50 110]
Transpose W.T:
 [[1 3]
 [2 4]]



**Why this output?**  
`@` is matrix multiplication. `T` is transpose.



### 3.11 Copies vs views (important gotcha)


In [52]:
base = np.arange(6)
view = base[2:5]
copy = base[2:5].copy()

view[:] = 99

print("base after modifying view:", base)
print("copy remains:", copy)

base after modifying view: [ 0  1 99 99 99  5]
copy remains: [2 3 4]



**Why this output?**  
Slicing often returns a view sharing memory with the original array.



### 3.12 Flattening arrays


In [53]:
M = np.arange(1, 7).reshape(2, 3)
print("M:\n", M)
print("ravel:", M.ravel())
print("flatten:", M.flatten())

M:
 [[1 2 3]
 [4 5 6]]
ravel: [1 2 3 4 5 6]
flatten: [1 2 3 4 5 6]



**Why this output?**  
`ravel()` may return a view; `flatten()` returns a copy.



<div style="background:#ecfeff; border-left: 6px solid #06b6d4; padding: 14px 16px; border-radius: 10px;">
  <h3 style="margin-top:0;">3.13 Mini example: feature scaling with NumPy</h3>
</div>


In [54]:
X = np.array([100, 120, 150, 200], dtype=float)

X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min)

print("Original:", X)
print("MinMax scaled:", X_scaled)

Original: [100. 120. 150. 200.]
MinMax scaled: [0.  0.2 0.5 1. ]



**Why this output?**  
We subtract the minimum and divide by the range to map values into `[0, 1]`.



<div style="background:#f0fdf4; border-left: 6px solid #22c55e; padding: 14px 16px; border-radius: 10px;">
  <h3 style="margin-top:0;">🧩 Practice: NumPy fundamentals for ML</h3>
  <ol>
    <li>Create a 5×3 array of random integers between 0 and 9.</li>
    <li>Compute the mean of each column.</li>
    <li>Standardize each column: (x - mean) / std.</li>
    <li>Use boolean masking to select values greater than 1 standard deviation.</li>
  </ol>
</div>



<div style="background: linear-gradient(90deg, #111827, #334155);
            color:white; padding: 18px 20px; border-radius: 14px;">
  <h2 style="margin: 0;">✅ What you now know</h2>
  <ul style="margin-top:10px;">
    <li>Core Python concepts that form the backbone of ML coding</li>
    <li>How Python types, control flow, and functions map to data/experiment work</li>
    <li>NumPy array creation, shapes, indexing, masking, broadcasting</li>
    <li>Aggregations, random reproducibility, and linear algebra essentials</li>
    <li>Key gotchas: views vs copies</li>
  </ul>
</div>



## 🚀 Next step

After this notebook, learners are ready for:
- Pandas data wrangling  
- Visualization for EDA  
- The first supervised models in scikit-learn  
